import type { AwardContractActionDefinition } from '../../types';

export const awardContractActionCatalogue: AwardContractActionDefinition[] = [
  { key: 'approve-award', label: 'Approve award', owner: 'BUYER', group: 'Awarding', targetRecordType: 'awardRecommendation' },
  { key: 'return-award', label: 'Return award', owner: 'BUYER', group: 'Awarding', targetRecordType: 'awardRecommendation' },
  { key: 'supplier-award-response', label: 'Respond to award', owner: 'SUPPLIER', group: 'Awarding', targetRecordType: 'awardNotice' },
  { key: 'contract-draft', label: 'Update contract draft', owner: 'BUYER', group: 'Formation', targetRecordType: 'contractVersion' },
  { key: 'clause-review', label: 'Review clause', owner: 'ANY', group: 'Formation', targetRecordType: 'contractClause' },
  { key: 'negotiation', label: 'Create negotiation point', owner: 'ANY', group: 'Formation', targetRecordType: 'contractNegotiation' },
  { key: 'owner-approval', label: 'Complete owner approval', owner: 'BUYER', group: 'Formation', targetRecordType: 'workflowApproval' },
  { key: 'signature-request', label: 'Signature request', owner: 'BUYER', group: 'Formation', targetRecordType: 'contractSignature' },
  { key: 'sign-buyer', label: 'Sign BUYER', owner: 'BUYER', group: 'Formation', targetRecordType: 'contractSignature' },
  { key: 'sign-supplier', label: 'Sign SUPPLIER', owner: 'SUPPLIER', group: 'Formation', targetRecordType: 'contractSignature' },
  { key: 'cmp', label: 'Maintain contract management plan (CMP)', owner: 'BUYER', group: 'Post-award', targetRecordType: 'contractManagementPlan', crossPartyVisibility: 'READ_ONLY', hiddenWhenReadOnly: ['contractManagerId', 'payload'] },
  { key: 'post-award-cmp', label: 'Contract management plan (CMP)', owner: 'BUYER', group: 'Post-award', targetRecordType: 'contractManagementPlan', crossPartyVisibility: 'READ_ONLY', hiddenWhenReadOnly: ['contractManagerId', 'payload'] },
  { key: 'contract-status', label: 'Contract status', owner: 'BUYER', group: 'Post-award', targetRecordType: 'contractStatus', crossPartyVisibility: 'STATUS_ONLY' },
  { key: 'activation-item-submission', label: 'Activation item submission', owner: 'SUPPLIER', group: 'Post-award', targetRecordType: 'contractActivationItem', crossPartyVisibility: 'READ_ONLY', hiddenWhenReadOnly: ['payload'] },
  { key: 'activation-review', label: 'Activation review', owner: 'BUYER', group: 'Post-award', targetRecordType: 'contractActivationItem', crossPartyVisibility: 'READ_ONLY', hiddenWhenReadOnly: ['payload'] },
  { key: 'activate-contract', label: 'Activate contract', owner: 'BUYER', group: 'Post-award', targetRecordType: 'contractActivation', crossPartyVisibility: 'READ_ONLY', hiddenWhenReadOnly: ['payload'] },
  { key: 'contract-obligation', label: 'Contract obligation', owner: 'BUYER', group: 'Post-award', targetRecordType: 'contractObligation', crossPartyVisibility: 'READ_ONLY', hiddenWhenReadOnly: ['payload'] },
  { key: 'evidence-requirement', label: 'Evidence requirement', owner: 'BUYER', group: 'Post-award', targetRecordType: 'contractEvidenceRequirement', crossPartyVisibility: 'READ_ONLY', hiddenWhenReadOnly: ['payload'] },
  { key: 'commencement', label: 'Commencement', owner: 'BUYER', group: 'Post-award', targetRecordType: 'contractCommencement', crossPartyVisibility: 'READ_ONLY', hiddenWhenReadOnly: ['payload'] },
  { key: 'milestone', label: 'Milestone', owner: 'BUYER', group: 'Delivery', targetRecordType: 'contractMilestone', crossPartyVisibility: 'READ_ONLY', hiddenWhenReadOnly: ['payload'] },
  { key: 'mobilization-update', label: 'Mobilization update', owner: 'BUYER', group: 'Delivery', targetRecordType: 'contractMobilization', crossPartyVisibility: 'READ_ONLY', hiddenWhenReadOnly: ['payload'] },
  { key: 'milestone-update', label: 'Milestone update', owner: 'BUYER', group: 'Delivery', targetRecordType: 'contractMilestone', crossPartyVisibility: 'READ_ONLY', hiddenWhenReadOnly: ['payload'] },
  { key: 'milestone-evidence', label: 'Milestone evidence', owner: 'SUPPLIER', group: 'Delivery', targetRecordType: 'contractMilestoneEvidence', crossPartyVisibility: 'READ_ONLY' },
  { key: 'deliverable', label: 'Submit deliverable', owner: 'SUPPLIER', group: 'Delivery', targetRecordType: 'contractDeliverable', crossPartyVisibility: 'READ_ONLY', hiddenWhenReadOnly: ['payload'] },
  { key: 'post-award-deliverable', label: 'Deliverable', owner: 'SUPPLIER', group: 'Delivery', targetRecordType: 'contractDeliverable', crossPartyVisibility: 'READ_ONLY', hiddenWhenReadOnly: ['payload'] },
  { key: 'goods-delivery-schedule', label: 'Goods delivery schedule', owner: 'BUYER', group: 'Delivery', targetRecordType: 'contractDeliverySchedule', crossPartyVisibility: 'READ_ONLY', hiddenWhenReadOnly: ['payload'] },
  { key: 'dispatch-notice', label: 'Dispatch notice', owner: 'SUPPLIER', group: 'Delivery', targetRecordType: 'contractDispatchNotice', crossPartyVisibility: 'READ_ONLY', hiddenWhenReadOnly: ['payload'] },
  { key: 'goods-receipt', label: 'Goods receipt', owner: 'BUYER', group: 'Delivery', targetRecordType: 'contractGoodsReceipt', crossPartyVisibility: 'READ_ONLY', hiddenWhenReadOnly: ['payload'] },
  { key: 'site-handover', label: 'Site handover', owner: 'BUYER', group: 'Delivery', targetRecordType: 'contractSiteHandover', crossPartyVisibility: 'READ_ONLY', hiddenWhenReadOnly: ['payload'] },
  { key: 'works-progress-report', label: 'Works progress report', owner: 'SUPPLIER', group: 'Delivery', targetRecordType: 'contractWorksProgressReport', crossPartyVisibility: 'READ_ONLY', hiddenWhenReadOnly: ['payload'] },
  { key: 'boq-measurement', label: 'BOQ measurement', owner: 'BUYER', group: 'Delivery', targetRecordType: 'contractBoqMeasurement', crossPartyVisibility: 'READ_ONLY', hiddenWhenReadOnly: ['payload'] },
  { key: 'interim-payment-certificate', label: 'Interim payment certificate', owner: 'BUYER', group: 'Delivery', targetRecordType: 'contractInterimPaymentCertificate', crossPartyVisibility: 'READ_ONLY', hiddenWhenReadOnly: ['payload'] },
  { key: 'service-level', label: 'Service level', owner: 'BUYER', group: 'Delivery', targetRecordType: 'contractServiceLevel', crossPartyVisibility: 'READ_ONLY', hiddenWhenReadOnly: ['payload'] },
  { key: 'service-period', label: 'Service period', owner: 'BUYER', group: 'Delivery', targetRecordType: 'contractServicePeriod', crossPartyVisibility: 'READ_ONLY', hiddenWhenReadOnly: ['payload'] },
  { key: 'service-report', label: 'Service report', owner: 'SUPPLIER', group: 'Delivery', targetRecordType: 'contractServiceReport', crossPartyVisibility: 'READ_ONLY', hiddenWhenReadOnly: ['payload'] },
  { key: 'consultancy-deliverable', label: 'Consultancy deliverable', owner: 'SUPPLIER', group: 'Delivery', targetRecordType: 'contractConsultancyDeliverable', crossPartyVisibility: 'READ_ONLY', hiddenWhenReadOnly: ['payload'] },
  { key: 'consultancy-deliverable-version', label: 'Consultancy deliverable version', owner: 'SUPPLIER', group: 'Delivery', targetRecordType: 'contractDeliverableVersion', crossPartyVisibility: 'READ_ONLY', hiddenWhenReadOnly: ['payload'] },
  { key: 'inspection', label: 'Record inspection', owner: 'BUYER', group: 'Inspections', targetRecordType: 'contractInspection', crossPartyVisibility: 'READ_ONLY', hiddenWhenReadOnly: ['payload'] },
  { key: 'post-award-inspection', label: 'Inspection', owner: 'BUYER', group: 'Inspections', targetRecordType: 'contractInspection', crossPartyVisibility: 'READ_ONLY', hiddenWhenReadOnly: ['payload'] },
  { key: 'goods-inspection', label: 'Goods inspection', owner: 'BUYER', group: 'Inspections', targetRecordType: 'contractGoodsInspection', crossPartyVisibility: 'READ_ONLY', hiddenWhenReadOnly: ['payload'] },
  { key: 'acceptance-certificate', label: 'Acceptance certificate', owner: 'BUYER', group: 'Inspections', targetRecordType: 'contractAcceptance', crossPartyVisibility: 'READ_ONLY', hiddenWhenReadOnly: ['payload'] },
  { key: 'works-defect', label: 'Works defect', owner: 'BUYER', group: 'Inspections', targetRecordType: 'contractDefect', crossPartyVisibility: 'READ_ONLY', hiddenWhenReadOnly: ['payload'] },
  { key: 'consultancy-review', label: 'Consultancy review', owner: 'BUYER', group: 'Inspections', targetRecordType: 'contractDeliverableReview', crossPartyVisibility: 'READ_ONLY', hiddenWhenReadOnly: ['payload'] },
  { key: 'payment-schedule', label: 'Payment schedule', owner: 'BUYER', group: 'Payments', targetRecordType: 'paymentSchedule', crossPartyVisibility: 'READ_ONLY', hiddenWhenReadOnly: ['payload'] },
  { key: 'invoice', label: 'Submit invoice', owner: 'SUPPLIER', group: 'Payments', targetRecordType: 'invoice', crossPartyVisibility: 'READ_ONLY', hiddenWhenReadOnly: ['payload'] },
  { key: 'invoice-submission', label: 'Invoice submission', owner: 'SUPPLIER', group: 'Payments', targetRecordType: 'invoice', crossPartyVisibility: 'READ_ONLY', hiddenWhenReadOnly: ['payload'] },
  { key: 'three-way-match', label: 'Three-way match', owner: 'BUYER', group: 'Payments', targetRecordType: 'threeWayMatch', crossPartyVisibility: 'READ_ONLY', hiddenWhenReadOnly: ['payload'] },
  { key: 'payment-review', label: 'Payment review', owner: 'BUYER', group: 'Payments', targetRecordType: 'payment', crossPartyVisibility: 'READ_ONLY', hiddenWhenReadOnly: ['payload'] },
  { key: 'invoice-status', label: 'Invoice status', owner: 'BUYER', group: 'Payments', targetRecordType: 'invoice', crossPartyVisibility: 'READ_ONLY', hiddenWhenReadOnly: ['payload'] },
  { key: 'payment-approval', label: 'Approve payment', owner: 'BUYER', group: 'Payments', targetRecordType: 'paymentApproval', crossPartyVisibility: 'READ_ONLY', hiddenWhenReadOnly: ['payload'] },
  { key: 'post-award-payment-approval', label: 'Payment approval', owner: 'BUYER', group: 'Payments', targetRecordType: 'paymentApproval', crossPartyVisibility: 'READ_ONLY', hiddenWhenReadOnly: ['payload'] },
  { key: 'payment-confirmation', label: 'Payment confirmation', owner: 'BUYER', group: 'Payments', targetRecordType: 'paymentConfirmation', crossPartyVisibility: 'READ_ONLY', hiddenWhenReadOnly: ['payload'] },
  { key: 'penalty-deduction', label: 'Penalty or deduction', owner: 'BUYER', group: 'Payments', targetRecordType: 'penaltyDeduction', crossPartyVisibility: 'READ_ONLY', hiddenWhenReadOnly: ['payload'] },
  { key: 'service-credit', label: 'Service credit', owner: 'BUYER', group: 'Payments', targetRecordType: 'serviceCredit', crossPartyVisibility: 'READ_ONLY', hiddenWhenReadOnly: ['payload'] },
  { key: 'risk', label: 'Risk', owner: 'BUYER', group: 'Risk', targetRecordType: 'contractRisk', crossPartyVisibility: 'READ_ONLY', hiddenWhenReadOnly: ['payload'] },
  { key: 'risk-update', label: 'Risk update', owner: 'BUYER', group: 'Risk', targetRecordType: 'contractRisk', crossPartyVisibility: 'READ_ONLY', hiddenWhenReadOnly: ['payload'] },
  { key: 'risk-forecast', label: 'Record risk forecast', owner: 'BUYER', group: 'Risk oversight', targetRecordType: 'riskForecast', crossPartyVisibility: 'HIDDEN' },
  { key: 'post-award-risk-forecast', label: 'Risk forecast', owner: 'BUYER', group: 'Risk oversight', targetRecordType: 'riskForecast', crossPartyVisibility: 'HIDDEN' },
  { key: 'non-conformance', label: 'Non-conformance', owner: 'BUYER', group: 'Risk', targetRecordType: 'nonConformance', crossPartyVisibility: 'READ_ONLY', hiddenWhenReadOnly: ['payload'] },
  { key: 'variation', label: 'Record variation', owner: 'ANY', group: 'Changes', targetRecordType: 'contractVariation' },
  { key: 'post-award-variation', label: 'Variation', owner: 'ANY', group: 'Changes', targetRecordType: 'contractVariation', crossPartyVisibility: 'READ_ONLY', hiddenWhenReadOnly: ['payload'] },
  { key: 'variation-update', label: 'Variation update', owner: 'BUYER', group: 'Changes', targetRecordType: 'contractVariation', crossPartyVisibility: 'READ_ONLY', hiddenWhenReadOnly: ['payload'] },
  { key: 'change-request', label: 'Change request', owner: 'ANY', group: 'Changes', targetRecordType: 'changeRequest', crossPartyVisibility: 'READ_ONLY', hiddenWhenReadOnly: ['payload'] },
  { key: 'issue', label: 'Issue', owner: 'ANY', group: 'Changes', targetRecordType: 'contractIssue', crossPartyVisibility: 'READ_ONLY', hiddenWhenReadOnly: ['payload'] },
  { key: 'issue-update', label: 'Issue update', owner: 'BUYER', group: 'Changes', targetRecordType: 'contractIssue', crossPartyVisibility: 'READ_ONLY', hiddenWhenReadOnly: ['payload'] },
  { key: 'dispute', label: 'Dispute', owner: 'ANY', group: 'Changes', targetRecordType: 'contractDispute', crossPartyVisibility: 'READ_ONLY', hiddenWhenReadOnly: ['payload'] },
  { key: 'dispute-update', label: 'Dispute update', owner: 'BUYER', group: 'Changes', targetRecordType: 'contractDispute', crossPartyVisibility: 'READ_ONLY', hiddenWhenReadOnly: ['payload'] },
  { key: 'claim', label: 'Claim', owner: 'ANY', group: 'Claims', targetRecordType: 'contractClaim', crossPartyVisibility: 'READ_ONLY', hiddenWhenReadOnly: ['payload'] },
  { key: 'claim-response', label: 'Claim response', owner: 'BUYER', group: 'Claims', targetRecordType: 'contractClaimResponse', crossPartyVisibility: 'READ_ONLY', hiddenWhenReadOnly: ['payload'] },
  { key: 'extension-request', label: 'Extension request', owner: 'ANY', group: 'Changes', targetRecordType: 'contractExtensionRequest', crossPartyVisibility: 'READ_ONLY', hiddenWhenReadOnly: ['payload'] },
  { key: 'contract-amendment', label: 'Contract amendment', owner: 'ANY', group: 'Changes', targetRecordType: 'contractAmendment', crossPartyVisibility: 'READ_ONLY', hiddenWhenReadOnly: ['payload'] },
  { key: 'termination', label: 'Manage termination', owner: 'BUYER', group: 'Termination', targetRecordType: 'contractTermination' },
  { key: 'post-award-termination', label: 'Termination', owner: 'BUYER', group: 'Termination', targetRecordType: 'contractTermination', crossPartyVisibility: 'READ_ONLY', hiddenWhenReadOnly: ['payload'] },
  { key: 'termination-update', label: 'Termination update', owner: 'BUYER', group: 'Termination', targetRecordType: 'contractTermination', crossPartyVisibility: 'READ_ONLY', hiddenWhenReadOnly: ['payload'] },
  { key: 'termination-notice', label: 'Termination notice', owner: 'BUYER', group: 'Termination', targetRecordType: 'contractTerminationNotice', crossPartyVisibility: 'READ_ONLY', hiddenWhenReadOnly: ['payload'] },
  { key: 'termination-evidence', label: 'Termination evidence', owner: 'SUPPLIER', group: 'Termination', targetRecordType: 'contractTerminationEvidence', crossPartyVisibility: 'READ_ONLY', hiddenWhenReadOnly: ['payload'] },
  { key: 'termination-valuation', label: 'Termination valuation', owner: 'BUYER', group: 'Termination', targetRecordType: 'contractTerminationValuation', crossPartyVisibility: 'READ_ONLY', hiddenWhenReadOnly: ['payload'] },
  { key: 'termination-settlement', label: 'Termination settlement', owner: 'BUYER', group: 'Termination', targetRecordType: 'contractTerminationSettlement', crossPartyVisibility: 'READ_ONLY', hiddenWhenReadOnly: ['payload'] },
  { key: 'replacement-procurement', label: 'Replacement procurement', owner: 'BUYER', group: 'Termination', targetRecordType: 'replacementProcurement', crossPartyVisibility: 'HIDDEN' },
  { key: 'warranty-defects', label: 'Warranty / defects', owner: 'ANY', group: 'Warranty', targetRecordType: 'contractWarranty', crossPartyVisibility: 'READ_ONLY', hiddenWhenReadOnly: ['payload'] },
  { key: 'security-guarantee', label: 'Security or guarantee', owner: 'BUYER', group: 'Documents', targetRecordType: 'contractSecurity', crossPartyVisibility: 'READ_ONLY', hiddenWhenReadOnly: ['payload'] },
  { key: 'required-document', label: 'Required document', owner: 'SUPPLIER', group: 'Documents', targetRecordType: 'requiredDocument', crossPartyVisibility: 'READ_ONLY', hiddenWhenReadOnly: ['payload'] },
  { key: 'closeout', label: 'Close out contract', owner: 'BUYER', group: 'Close-out', targetRecordType: 'contractCloseout', crossPartyVisibility: 'READ_ONLY', hiddenWhenReadOnly: ['payload', 'signatureKeyphrase'] },
  { key: 'post-award-closeout', label: 'Close-out', owner: 'BUYER', group: 'Close-out', targetRecordType: 'contractCloseout', crossPartyVisibility: 'READ_ONLY', hiddenWhenReadOnly: ['payload', 'signatureKeyphrase'] },
  { key: 'performance', label: 'Score supplier performance', owner: 'BUYER', group: 'Performance', targetRecordType: 'supplierPerformance', crossPartyVisibility: 'READ_ONLY', hiddenWhenReadOnly: ['payload'] },
  { key: 'supplier-performance', label: 'Supplier performance', owner: 'BUYER', group: 'Performance', targetRecordType: 'supplierPerformance', crossPartyVisibility: 'READ_ONLY', hiddenWhenReadOnly: ['payload'] },
  { key: 'performance-score', label: 'Performance score', owner: 'BUYER', group: 'Performance', targetRecordType: 'performanceScore', crossPartyVisibility: 'READ_ONLY', hiddenWhenReadOnly: ['payload'] },
  { key: 'admin-supplier-risk-profile', label: 'Maintain admin supplier risk profile', owner: 'ADMIN', group: 'Compliance oversight', targetRecordType: 'supplierRiskProfile' },
  { key: 'supplier-risk-profile', label: 'Update supplier risk profile', owner: 'BUYER', group: 'Performance', targetRecordType: 'supplierRiskProfile', crossPartyVisibility: 'HIDDEN' },
  { key: 'post-award-supplier-risk-profile', label: 'Supplier risk profile', owner: 'BUYER', group: 'Performance', targetRecordType: 'supplierRiskProfile', crossPartyVisibility: 'HIDDEN' },
  { key: 'collusion-alert', label: 'Record collusion alert', owner: 'ADMIN', group: 'Compliance oversight', targetRecordType: 'collusionAlert' },
  { key: 'compliance-review', label: 'Open compliance review', owner: 'ADMIN', group: 'Compliance oversight', targetRecordType: 'complianceReview' },
  { key: 'violation-case', label: 'Record violation case', owner: 'ADMIN', group: 'Compliance oversight', targetRecordType: 'violationCase' },
  { key: 'violation-evidence', label: 'Attach violation evidence', owner: 'ADMIN', group: 'Compliance oversight', targetRecordType: 'violationEvidence' },
  { key: 'enforcement-record', label: 'Record enforcement action', owner: 'ADMIN', group: 'Compliance oversight', targetRecordType: 'enforcementRecord' },
  { key: 'appeal-record', label: 'Record appeal', owner: 'ADMIN', group: 'Compliance oversight', targetRecordType: 'appealRecord' },
  { key: 'trust-tier-adjustment', label: 'Adjust trust tier', owner: 'ADMIN', group: 'Compliance oversight', targetRecordType: 'trustTierAdjustment' }
];

export function actionDefinitionForTitle(title: string) {
  const normalized = title.toLowerCase();
  return awardContractActionCatalogue.find((item) => item.label.toLowerCase() === normalized)
    ?? awardContractActionCatalogue.find((item) => normalized.includes(item.key.replace(/-/g, ' ')) || normalized.includes(item.label.toLowerCase()));
}
