import type { OfficialPdfRow, OfficialPdfSection } from './officialPdfRenderer.js';
import type { OfficialTemplateDefinition } from './officialTemplates.js';
import type { OfficialValidationWarning } from './types.js';

export type OfficialSourceSnapshot = {
  sourceModule: string;
  sourceEntityType: string;
  sourceEntityId: string;
  ownerOrgId?: string | null;
  visibleOrgIds?: string[];
  publicVisible?: boolean;
  ownerName?: string | null;
  title: string;
  reference: string;
  documentStatus?: string | null;
  procurementType?: string | null;
  financialYear?: string | null;
  closingDate?: string | Date | null;
  tenderReference?: string | null;
  contractReference?: string | null;
  supplierName?: string | null;
  amount?: string | number | null;
  currency?: string | null;
  description?: string | null;
  method?: string | null;
  location?: string | null;
  items?: OfficialPdfRow[];
  documents?: OfficialPdfRow[];
  timeline?: OfficialPdfRow[];
  workflow?: OfficialPdfRow[];
  criteria?: OfficialPdfRow[];
  approvals?: OfficialPdfRow[];
  signatures?: OfficialPdfRow[];
  annexes?: OfficialPdfRow[];
  raw?: Record<string, unknown>;
};

export function validateOfficialSource(template: OfficialTemplateDefinition, source: OfficialSourceSnapshot): OfficialValidationWarning[] {
  return template.requiredFields
    .filter((field) => !hasPathValue(source, field.path))
    .map((field) => ({
      path: field.path,
      label: field.label,
      message: `${field.label} is required before an official-ready ${template.name} can be generated.`
    }));
}

export function buildOfficialPdfSections(template: OfficialTemplateDefinition, source: OfficialSourceSnapshot): OfficialPdfSection[] {
  return template.sections.map((templateSection) => {
    const rows = rowsForSection(templateSection.key, source);
    const bullets = bulletsForSection(templateSection.key, source);
    return {
      title: templateSection.title,
      intro: templateSection.description,
      paragraphs: sectionParagraphs(templateSection.key, template.name, source),
      rows: rows.length ? rows : [{ label: 'Source data', value: 'No structured workflow data was available for this section.' }],
      bullets
    };
  });
}

export function documentControlRows(input: {
  template: OfficialTemplateDefinition;
  source: OfficialSourceSnapshot;
  versionNo: number;
  status: string;
  generatedAt: Date;
  generatedByUserId?: string;
}) {
  return compactRows([
    row('Template code', input.template.code),
    row('Template version', input.template.version),
    row('Document type', input.template.documentType),
    row('Procurement type', input.source.procurementType ?? input.template.procurementType ?? 'Not applicable'),
    row('Jurisdiction', 'United Republic of Tanzania'),
    row('Source authority', `${input.template.sourceAuthority} standard documents and procedural forms`),
    row('Source URL', input.template.sourceUrl),
    row('Source module', input.source.sourceModule),
    row('Source entity', `${input.source.sourceEntityType}:${input.source.sourceEntityId}`),
    row('Generated version', String(input.versionNo)),
    row('Generated by user', input.generatedByUserId ?? 'System or unavailable'),
    row('Generated at', input.generatedAt.toISOString()),
    row('Status', input.status),
    row('Official status note', 'Draft or unsigned until approval/signature marks this immutable version as official')
  ]);
}

export function validationWarningRows(warnings: OfficialValidationWarning[]) {
  return warnings.map((warning) => row(warning.label, `${warning.message} Path: ${warning.path}`));
}

export function overviewRows(source: OfficialSourceSnapshot) {
  return compactRows([
    row('Title', source.title),
    row('Reference', source.reference),
    row('Procuring entity', source.ownerName),
    row('Workflow status', source.documentStatus),
    row('Procurement type', source.procurementType),
    row('Tender reference', source.tenderReference),
    row('Contract reference', source.contractReference),
    row('Supplier or bidder', source.supplierName),
    row('Procurement method', source.method),
    row('Financial year', source.financialYear),
    row('Closing date', formatValue(source.closingDate)),
    row('Amount', money(source.amount, source.currency)),
    row('Currency', source.currency),
    row('Location', source.location),
    row('Description', source.description)
  ]);
}

export function row(label: string, value: unknown): OfficialPdfRow {
  return { label, value: formatValue(value) };
}

export function compactRows(rows: OfficialPdfRow[]) {
  return rows.filter((entry) => entry.value.trim() !== '' && entry.value !== 'Not specified');
}

export function formatValue(value: unknown): string {
  if (value === null || value === undefined) return 'Not specified';
  if (value instanceof Date) return value.toISOString();
  if (typeof value === 'bigint') return value.toString();
  if (typeof value === 'number') return Number.isFinite(value) ? String(value) : 'Not specified';
  if (typeof value === 'boolean') return value ? 'Yes' : 'No';
  if (typeof value === 'string') return value.trim() || 'Not specified';
  if (Array.isArray(value)) {
    const rendered = value.map(formatValue).filter((item) => item !== 'Not specified');
    return rendered.length ? rendered.join('; ') : 'Not specified';
  }
  if (typeof value === 'object' && 'toString' in value && value.constructor?.name === 'Decimal') {
    return String(value);
  }
  if (typeof value === 'object') {
    const entries = Object.entries(value as Record<string, unknown>)
      .filter(([, child]) => isMeaningful(child))
      .slice(0, 18)
      .map(([key, child]) => `${humanize(key)}: ${formatValue(child)}`);
    return entries.length ? entries.join('; ') : 'Not specified';
  }
  return String(value);
}

export function money(amount: unknown, currency?: string | null) {
  if (!isMeaningful(amount)) return 'Not specified';
  const numeric = Number(amount);
  if (Number.isFinite(numeric)) return `${currency || 'TZS'} ${numeric.toLocaleString('en-US')}`;
  return `${currency || ''} ${formatValue(amount)}`.trim();
}

export function humanize(value: string) {
  return value
    .replace(/([a-z])([A-Z])/g, '$1 $2')
    .replace(/[_-]+/g, ' ')
    .replace(/\s+/g, ' ')
    .trim()
    .replace(/^./, (letter) => letter.toUpperCase());
}

function rowsForSection(key: string, source: OfficialSourceSnapshot): OfficialPdfRow[] {
  const overview = overviewRows(source);
  const control = compactRows([
    row('Generated source module', source.sourceModule),
    row('Generated source entity', `${source.sourceEntityType}:${source.sourceEntityId}`),
    row('Current workflow status', source.documentStatus),
    row('Owner organization id', source.ownerOrgId)
  ]);
  const sourceRawRows = source.raw ? objectRows(source.raw) : [];

  switch (key) {
    case 'cover':
    case 'summary':
    case 'details':
    case 'background':
    case 'authority':
    case 'notice':
    case 'record':
    case 'mandate':
    case 'agreement':
      return overview;
    case 'lines':
    case 'line':
    case 'requirements':
    case 'scope':
    case 'technical':
    case 'delivery':
    case 'pricing':
    case 'boq':
    case 'tor':
    case 'items':
    case 'deliverables':
    case 'levels':
    case 'resources':
    case 'programme':
      return source.items?.length ? source.items : sourceRawRows;
    case 'documents':
    case 'annexes':
    case 'forms':
    case 'drawings':
      return source.documents?.length ? source.documents : source.annexes ?? [];
    case 'schedule':
    case 'submission':
    case 'dataSheet':
    case 'instructions':
    case 'contacts':
      return compactRows([...overview, ...(source.timeline ?? [])]);
    case 'methodology':
    case 'responsiveness':
    case 'evaluation':
    case 'technicalProposal':
    case 'financialProposal':
    case 'financial':
    case 'recommendation':
    case 'justification':
      return compactRows([...(source.criteria ?? []), ...(source.workflow ?? []), ...overview]);
    case 'approvals':
    case 'approval':
    case 'acknowledgement':
    case 'certification':
      return source.approvals?.length ? source.approvals : control;
    case 'signatures':
      return source.signatures?.length ? source.signatures : control;
    case 'integrity':
    case 'linkage':
    case 'effect':
    case 'limits':
    case 'agenda':
    case 'outcome':
    case 'price':
    case 'conditions':
    case 'changes':
    case 'exceptions':
    case 'index':
      return compactRows([...(source.workflow ?? []), ...(source.timeline ?? []), ...control]);
    default:
      return compactRows([...overview, ...sourceRawRows]);
  }
}

function bulletsForSection(key: string, source: OfficialSourceSnapshot): string[] | undefined {
  if (key === 'integrity') {
    return [
      'Every generated PDF version is stored immutably with a SHA-256 checksum in the document version record.',
      'A later data change must generate a new version; old versions are retained unless explicitly voided.',
      'Approval and signature actions apply only to the exact generated version identified in this document.'
    ];
  }
  if (key === 'conditions') {
    return [
      'General conditions, special conditions, and contract-specific instructions should be read together with the tender or contract data sheet.',
      'Where platform data and uploaded annexes differ, the approved signed version and its audit trail should control.'
    ];
  }
  if (key === 'evaluation' || key === 'methodology') {
    return [
      'Evaluation should be applied consistently against the published tender requirements and criteria.',
      'Clarifications must not materially change the submitted bid or the evaluation basis.'
    ];
  }
  if (key === 'forms') {
    return ['Required forms and declarations should be completed, signed where applicable, and submitted through the authorised procurement channel.'];
  }
  if (!source.raw && key === 'index') return ['No additional archive index data was provided by the source workflow.'];
  return undefined;
}

function sectionParagraphs(key: string, templateName: string, source: OfficialSourceSnapshot) {
  const officialReady = `This ${templateName} section is populated from ProcureX workflow data for ${source.reference}. The wording is intended for official-ready procurement records and should be reviewed before approval.`;
  if (key === 'cover') {
    return [
      officialReady,
      'The document is generated as a controlled PDF and remains draft, unsigned, or pending approval until the authorised workflow completes.'
    ];
  }
  if (key === 'integrity') {
    return [
      'The system records the generated version number, source entity, checksum, generator user, and approval or signature metadata. This supports traceability and avoids overwriting prior versions.'
    ];
  }
  return [officialReady];
}

function objectRows(value: Record<string, unknown>) {
  return Object.entries(value)
    .filter(([, child]) => isMeaningful(child))
    .slice(0, 24)
    .map(([key, child]) => row(humanize(key), child));
}

function hasPathValue(source: OfficialSourceSnapshot, path: string): boolean {
  const value = path.split('.').reduce<unknown>((current, part) => {
    if (!current || typeof current !== 'object') return undefined;
    return (current as Record<string, unknown>)[part];
  }, source);
  return isMeaningful(value);
}

function isMeaningful(value: unknown): boolean {
  if (value === null || value === undefined) return false;
  if (value instanceof Date) return true;
  if (Array.isArray(value)) return value.some(isMeaningful);
  if (typeof value === 'object' && 'toString' in value && value.constructor?.name === 'Decimal') return String(value).trim() !== '';
  if (typeof value === 'object') return Object.values(value as Record<string, unknown>).some(isMeaningful);
  return String(value).trim() !== '';
}
