/* Supports the documents server workflow with reusable logic kept close to the module that owns it. */
import { PDFDocument, StandardFonts, degrees, rgb, type PDFFont, type PDFPage } from 'pdf-lib';

export type OfficialPdfRow = {
  label: string;
  value: string;
};

export type OfficialPdfSection = {
  title: string;
  intro?: string;
  paragraphs?: string[];
  rows?: OfficialPdfRow[];
  bullets?: string[];
};

export type OfficialPdfInput = {
  title: string;
  subtitle: string;
  reference: string;
  status: string;
  generatedAt: Date;
  metadataRows: OfficialPdfRow[];
  sections: OfficialPdfSection[];
  signatureBlocks?: string[];
  validationWarnings?: OfficialPdfRow[];
  watermark?: string;
};

const pageSize: [number, number] = [595.28, 841.89];
const margin = 48;
const bottomMargin = 62;
const contentWidth = pageSize[0] - margin * 2;
const bodySize = 9.6;
const smallSize = 8;
const headingSize = 14;

export async function renderOfficialPdf(input: OfficialPdfInput): Promise<Buffer> {
  const pdf = await PDFDocument.create();
  pdf.setTitle(input.title);
  pdf.setAuthor('ProcureX Official Document Generator');
  pdf.setSubject(`${input.subtitle} - ${input.reference}`);
  pdf.setProducer('ProcureX server official-documents module');
  pdf.setCreator('ProcureX');
  pdf.setCreationDate(input.generatedAt);
  pdf.setModificationDate(input.generatedAt);

  const regular = await pdf.embedFont(StandardFonts.Helvetica);
  const bold = await pdf.embedFont(StandardFonts.HelveticaBold);
  const oblique = await pdf.embedFont(StandardFonts.HelveticaOblique);

  const writer = new PdfWriter(pdf, regular, bold, oblique);
  writer.addCover(input);
  writer.addSection({
    title: 'Document Control',
    intro: 'This PDF was generated by the server-side official document system. It is immutable once stored and remains draft or unsigned until the required approval or signature action marks this specific version as official.',
    rows: input.metadataRows
  });

  if (input.validationWarnings?.length) {
    writer.addSection({
      title: 'Blocking Validation Report',
      intro: 'The requested document is not official-ready because required information is missing. Complete the fields below and generate a new version before approval or signature.',
      rows: input.validationWarnings
    });
  }

  input.sections.forEach((section, index) => {
    writer.addSection({
      ...section,
      title: `${index + 1}. ${section.title}`
    });
  });

  writer.addSection({
    title: 'Certification and Signature Blocks',
    intro: 'The following spaces are reserved for authorised review, approval, and signing. Electronic approval or signature metadata is recorded separately in the immutable document version record.',
    bullets: input.signatureBlocks?.length ? input.signatureBlocks : ['Prepared by', 'Reviewed by', 'Approved by', 'Authorised signatory']
  });

  writer.drawFooters(input);
  return Buffer.from(await pdf.save({ useObjectStreams: false }));
}

class PdfWriter {
  private page: PDFPage;
  private y = pageSize[1] - margin;

  constructor(
    private readonly pdf: PDFDocument,
    private readonly regular: PDFFont,
    private readonly bold: PDFFont,
    private readonly oblique: PDFFont
  ) {
    this.page = this.pdf.addPage(pageSize);
  }

  addCover(input: OfficialPdfInput) {
    this.y = pageSize[1] - 78;
    this.drawStatus(input.status, input.watermark);
    this.drawText('UNITED REPUBLIC OF TANZANIA', margin, this.y, this.bold, 10, rgb(0.12, 0.18, 0.28));
    this.y -= 19;
    this.drawText('Official-Ready Procurement Document', margin, this.y, this.regular, 10, rgb(0.28, 0.34, 0.43));
    this.y -= 46;
    this.drawWrapped(input.title, this.bold, 24, rgb(0.06, 0.11, 0.2), 28);
    this.y -= 5;
    this.drawWrapped(input.subtitle, this.regular, 12, rgb(0.22, 0.28, 0.38), 17);
    this.y -= 25;
    this.drawKeyValueBox([
      { label: 'Reference', value: input.reference },
      { label: 'Generated', value: input.generatedAt.toISOString() },
      { label: 'Status', value: input.status },
      { label: 'Source standard', value: 'Tanzania PPRA/NeST terminology and procurement lifecycle structure' }
    ]);
    this.y -= 28;
    this.drawWrapped(
      'This document contains standard official wording and sections populated from platform workflow data. It may be opened or downloaded as a PDF. It is not legally official until the required approval or signature workflow marks this exact generated version as official.',
      this.oblique,
      10,
      rgb(0.22, 0.28, 0.38),
      15
    );
    this.newPage();
  }

  addSection(section: OfficialPdfSection) {
    this.ensureSpace(110);
    this.drawText(section.title, margin, this.y, this.bold, headingSize, rgb(0.08, 0.14, 0.23));
    this.y -= 17;
    this.drawRule();
    if (section.intro) {
      this.drawWrapped(section.intro, this.regular, bodySize, rgb(0.18, 0.24, 0.34), 13.5);
      this.y -= 4;
    }
    for (const paragraph of section.paragraphs ?? []) {
      this.drawWrapped(paragraph, this.regular, bodySize, rgb(0.16, 0.22, 0.31), 13.5);
      this.y -= 3;
    }
    if (section.rows?.length) this.drawRows(section.rows);
    if (section.bullets?.length) this.drawBullets(section.bullets);
    this.y -= 11;
  }

  drawFooters(input: OfficialPdfInput) {
    const pages = this.pdf.getPages();
    pages.forEach((page, index) => {
      const footer = `ProcureX official-ready document | ${input.reference} | ${input.status} | Page ${index + 1} of ${pages.length}`;
      page.drawLine({
        start: { x: margin, y: 41 },
        end: { x: pageSize[0] - margin, y: 41 },
        thickness: 0.5,
        color: rgb(0.76, 0.8, 0.86)
      });
      page.drawText(footer, {
        x: margin,
        y: 28,
        size: smallSize,
        font: this.regular,
        color: rgb(0.35, 0.4, 0.5)
      });
    });
  }

  private drawStatus(status: string, watermark?: string) {
    this.page.drawRectangle({
      x: pageSize[0] - margin - 130,
      y: this.y - 14,
      width: 130,
      height: 30,
      borderColor: rgb(0.3, 0.42, 0.66),
      borderWidth: 1,
      color: rgb(0.94, 0.97, 1)
    });
    this.page.drawText(status.replace(/_/g, ' '), {
      x: pageSize[0] - margin - 119,
      y: this.y - 3,
      size: 10,
      font: this.bold,
      color: rgb(0.09, 0.17, 0.32)
    });
    if (watermark) {
      this.page.drawText(watermark, {
        x: 92,
        y: 412,
        size: 46,
        font: this.bold,
        color: rgb(0.9, 0.92, 0.95),
        rotate: degrees(35)
      });
    }
  }

  private drawKeyValueBox(rows: OfficialPdfRow[]) {
    const rowHeight = 25;
    const height = rows.length * rowHeight + 2;
    this.ensureSpace(height + 20);
    this.page.drawRectangle({
      x: margin,
      y: this.y - height,
      width: contentWidth,
      height,
      borderColor: rgb(0.75, 0.8, 0.88),
      borderWidth: 0.7,
      color: rgb(0.98, 0.99, 1)
    });
    let rowY = this.y - 18;
    for (const row of rows) {
      this.drawText(row.label, margin + 12, rowY, this.bold, 8.8, rgb(0.23, 0.29, 0.39));
      this.drawWrappedAt(row.value || 'Not specified', margin + 165, rowY, contentWidth - 180, this.regular, 8.8, rgb(0.12, 0.18, 0.28), 11);
      rowY -= rowHeight;
    }
    this.y -= height + 8;
  }

  private drawRows(rows: OfficialPdfRow[]) {
    const labelWidth = 150;
    for (const row of rows) {
      let valueLines = wrapText(row.value || 'Not specified', this.regular, bodySize, contentWidth - labelWidth - 24);
      let firstChunk = true;
      while (valueLines.length) {
        this.ensureSpace(34);
        const availableLines = Math.max(1, Math.floor((this.y - bottomMargin - 10) / 12));
        const chunk = valueLines.slice(0, availableLines);
        valueLines = valueLines.slice(chunk.length);
        const startY = this.y;
        const height = Math.max(24, chunk.length * 12 + 10);
        this.page.drawRectangle({
          x: margin,
          y: this.y - height,
          width: contentWidth,
          height,
          borderColor: rgb(0.82, 0.86, 0.92),
          borderWidth: 0.45
        });
        this.page.drawRectangle({
          x: margin,
          y: this.y - height,
          width: labelWidth,
          height,
          color: rgb(0.96, 0.98, 1),
          borderColor: rgb(0.82, 0.86, 0.92),
          borderWidth: 0.45
        });
        const label = firstChunk ? row.label : `${row.label} (continued)`;
        wrapText(label, this.bold, 8.6, labelWidth - 16).slice(0, Math.max(1, Math.floor((height - 8) / 10.5))).forEach((line, index) => {
          this.drawText(line, margin + 8, startY - 14 - index * 10.5, this.bold, 8.6, rgb(0.18, 0.24, 0.33));
        });
        chunk.forEach((line, index) => {
          this.drawText(line, margin + labelWidth + 12, startY - 14 - index * 12, this.regular, bodySize, rgb(0.14, 0.2, 0.3));
        });
        this.y -= height;
        firstChunk = false;
      }
    }
  }

  private drawBullets(bullets: string[]) {
    for (const bullet of bullets) {
      this.ensureSpace(22);
      const lines = wrapText(bullet, this.regular, bodySize, contentWidth - 18);
      this.drawText('-', margin + 3, this.y, this.bold, bodySize, rgb(0.13, 0.2, 0.32));
      lines.forEach((line, index) => {
        this.drawText(line, margin + 18, this.y - index * 12, this.regular, bodySize, rgb(0.14, 0.2, 0.3));
      });
      this.y -= Math.max(15, lines.length * 12 + 4);
    }
  }

  private drawWrapped(text: string, font: PDFFont, size: number, color: ReturnType<typeof rgb>, leading: number) {
    this.drawWrappedAt(text, margin, this.y, contentWidth, font, size, color, leading);
  }

  private drawWrappedAt(text: string, x: number, startY: number, width: number, font: PDFFont, size: number, color: ReturnType<typeof rgb>, leading: number) {
    const lines = wrapText(text, font, size, width);
    let nextY = startY;
    for (const line of lines) {
      this.ensureSpaceAt(nextY);
      if (nextY !== this.y && nextY < bottomMargin) nextY = this.y;
      this.drawText(line, x, nextY, font, size, color);
      nextY -= leading;
    }
    this.y = Math.min(this.y, nextY);
  }

  private drawText(text: string, x: number, y: number, font: PDFFont, size: number, color: ReturnType<typeof rgb>) {
    this.page.drawText(cleanPdfText(text), { x, y, size, font, color });
  }

  private drawRule() {
    this.page.drawLine({
      start: { x: margin, y: this.y + 7 },
      end: { x: margin + contentWidth, y: this.y + 7 },
      thickness: 0.7,
      color: rgb(0.72, 0.78, 0.86)
    });
    this.y -= 9;
  }

  private ensureSpace(height: number) {
    if (this.y - height < bottomMargin) this.newPage();
  }

  private ensureSpaceAt(y: number) {
    if (y < bottomMargin) this.newPage();
  }

  private newPage() {
    this.page = this.pdf.addPage(pageSize);
    this.y = pageSize[1] - margin;
  }
}

function wrapText(text: string, font: PDFFont, size: number, width: number) {
  const value = cleanPdfText(text).replace(/\s+/g, ' ').trim();
  if (!value) return ['Not specified'];
  const words = value.split(' ');
  const lines: string[] = [];
  let line = '';
  for (const word of words) {
    const next = line ? `${line} ${word}` : word;
    if (font.widthOfTextAtSize(next, size) <= width) {
      line = next;
      continue;
    }
    if (line) lines.push(line);
    if (font.widthOfTextAtSize(word, size) <= width) {
      line = word;
      continue;
    }
    const chunks = chunkLongWord(word, font, size, width);
    lines.push(...chunks.slice(0, -1));
    line = chunks.at(-1) ?? '';
  }
  if (line) lines.push(line);
  return lines;
}

function chunkLongWord(word: string, font: PDFFont, size: number, width: number) {
  const chunks: string[] = [];
  let current = '';
  for (const char of word) {
    const next = `${current}${char}`;
    if (font.widthOfTextAtSize(next, size) <= width) {
      current = next;
    } else {
      if (current) chunks.push(current);
      current = char;
    }
  }
  if (current) chunks.push(current);
  return chunks;
}

function cleanPdfText(value: string) {
  return String(value ?? '')
    .replace(/[^\x09\x0a\x0d\x20-\x7e]/g, ' ')
    .replace(/\s+/g, ' ')
    .trim();
}
