import { Router } from 'express';
import { rateLimit } from 'express-rate-limit';
import { createApiMutationRateLimitOptions } from '../../security/rateLimit.js';
import { ModuleController } from './controller.js';

export function createModuleRouter() {
  const router = Router();
  const controller = new ModuleController();
  const awardMutationLimit = rateLimit(createApiMutationRateLimitOptions('award-contract-mutation'));
  const sampleMutationLimit = rateLimit(createApiMutationRateLimitOptions('award-contract-sample-mutation'));

  router.get('/', controller.status);
  router.get('/dashboard', controller.dashboard);

  router.get('/recommendations', controller.listRecommendations);
  router.get('/recommendations/:id', controller.recommendation);
  router.get('/recommendations/:id/evaluation-report', controller.evaluationReport);
  router.patch('/recommendations/:id/draft', awardMutationLimit, controller.saveAwardDecisionDraft);
  router.post('/recommendations/:id/approve', awardMutationLimit, controller.approveRecommendation);
  router.post('/recommendations/:id/return', awardMutationLimit, controller.returnRecommendation);
  router.put('/recommendations/:id/approval-route', awardMutationLimit, controller.upsertAwardApprovalRoute);
  router.put('/recommendations/:id/approval-steps', awardMutationLimit, controller.upsertAwardApprovalStep);
  router.post('/recommendations/:id/tie-breakers', awardMutationLimit, controller.createAwardTieBreaker);
  router.put('/recommendations/:id/delivery-feasibility', awardMutationLimit, controller.upsertDeliveryFeasibility);
  router.put('/recommendations/:id/standstill', awardMutationLimit, controller.upsertStandstillPeriod);
  router.post('/recommendations/:id/notifications', awardMutationLimit, controller.createAwardNotification);
  router.post('/recommendations/:id/budget-commitments', awardMutationLimit, controller.createBudgetCommitmentForRecommendation);
  router.put('/recommendations/:id/clauses', awardMutationLimit, controller.upsertAwardClause);
  router.post('/recommendations/:id/negotiations', awardMutationLimit, controller.createAwardNegotiation);
  router.post('/recommendations/:id/bid-pack', awardMutationLimit, controller.generateAwardBidPack);
  router.post('/recommendations/:id/settle', awardMutationLimit, controller.settleAwardGroup);

  router.post('/notices/:id/respond', awardMutationLimit, controller.respondToNotice);
  router.post('/notices/:id/cancel', awardMutationLimit, controller.cancelAwardNotice);
  router.post('/notices/:id/reissue', awardMutationLimit, controller.reissueAwardNotice);

  router.post('/tenders/:tenderId/contract-draft', awardMutationLimit, controller.prepareTenderContractDraft);

  router.get('/samples', controller.listSamples);
  router.get('/samples/:sampleId', controller.sample);
  router.post('/samples/:sampleId/receive', sampleMutationLimit, controller.receiveSample);
  router.post('/samples/:sampleId/verify', sampleMutationLimit, controller.verifySample);
  router.post('/samples/:sampleId/custody-transfer', sampleMutationLimit, controller.transferSampleCustody);
  router.post('/samples/:sampleId/evaluations', sampleMutationLimit, controller.evaluateSample);
  router.post('/samples/:sampleId/tests', sampleMutationLimit, controller.createSampleTest);
  router.post('/samples/:sampleId/clarifications', sampleMutationLimit, controller.requestSampleClarification);
  router.post('/samples/:sampleId/return', sampleMutationLimit, controller.returnSample);
  router.post('/samples/:sampleId/retain', sampleMutationLimit, controller.retainSample);
  router.post('/samples/:sampleId/dispose', sampleMutationLimit, controller.disposeSample);

  router.get('/contracts', controller.listContracts);
  router.get('/contracts/:id', controller.contract);
  router.get('/contracts/:id/documents', controller.contractDocuments);
  router.post('/contracts/:id/documents', controller.uploadContractDocument);
  router.post('/contracts/:id/versions', controller.createContractVersion);
  router.post('/contracts/:id/send-for-negotiation', controller.sendContractForNegotiation);
  router.put('/contracts/:id/clauses', controller.upsertClause);
  router.delete('/contracts/:id/clauses/:itemId', controller.deleteClause);
  router.post('/contracts/:id/negotiations', controller.createNegotiation);
  router.patch('/contracts/:id/negotiations/:itemId', controller.updateNegotiation);
  router.post('/contracts/:id/signatures', controller.createSignatureRequests);
  router.post('/contracts/:id/signatures/:signatureId/sign', controller.signContractSignature);
  router.post('/contracts/:id/milestones', controller.createMilestone);
  router.patch('/contracts/:id/milestones/:milestoneId', controller.updateMilestone);
  router.post('/contracts/:id/milestones/:milestoneId/evidence', controller.addMilestoneEvidence);
  router.patch('/contracts/:id/status', controller.updateContractStatus);
  router.put('/contracts/:id/management-plan', controller.upsertManagementPlan);
  router.put('/contracts/:id/commencement', controller.upsertCommencement);
  router.post('/contracts/:id/non-conformances', controller.createNonConformance);
  router.post('/contracts/:id/securities', controller.createContractSecurity);
  router.post('/contracts/:id/penalties', controller.createContractPenalty);
  router.post('/contracts/:id/change-requests', controller.createContractChangeRequest);
  router.patch('/contracts/:id/mobilization/:itemId', controller.updateMobilizationItem);
  router.post('/contracts/:id/deliverables', controller.createDeliverable);
  router.post('/contracts/:id/acceptances', controller.createAcceptance);
  router.post('/contracts/:id/inspections', controller.createInspection);
  router.post('/contracts/:id/goods-inspections', controller.createGoodsInspection);
  router.post('/contracts/:id/invoices', controller.createInvoice);
  router.post('/contracts/:id/payment-schedules', controller.createPaymentSchedule);
  router.post('/contracts/:id/payments', controller.createPayment);
  router.put('/contracts/:id/three-way-match', controller.upsertThreeWayMatch);
  router.post('/contracts/:id/payment-approvals', controller.createPaymentApproval);
  router.post('/contracts/:id/payment-confirmations', controller.createPaymentConfirmation);
  router.post('/contracts/:id/performance-scores', controller.createPerformanceScore);
  router.post('/contracts/:id/risk-forecasts', controller.createRiskForecast);
  router.put('/contracts/:id/supplier-risk-profile', controller.upsertSupplierRiskProfile);
  router.post('/contracts/:id/risks', controller.createRisk);
  router.patch('/contracts/:id/risks/:itemId', controller.updateRisk);
  router.post('/contracts/:id/variations', controller.createVariation);
  router.patch('/contracts/:id/variations/:itemId', controller.updateVariation);
  router.post('/contracts/:id/issues', controller.createIssue);
  router.patch('/contracts/:id/issues/:itemId', controller.updateIssue);
  router.post('/contracts/:id/disputes', controller.createDispute);
  router.patch('/contracts/:id/disputes/:itemId', controller.updateDispute);
  router.post('/contracts/:id/terminations', controller.createTermination);
  router.patch('/contracts/:id/terminations/:terminationId', controller.updateTermination);
  router.post('/contracts/:id/terminations/:terminationId/notices', controller.addTerminationNotice);
  router.post('/contracts/:id/terminations/:terminationId/evidence', controller.addTerminationEvidence);
  router.put('/contracts/:id/terminations/:terminationId/valuation', controller.upsertTerminationValuation);
  router.put('/contracts/:id/terminations/:terminationId/settlement', controller.upsertTerminationSettlement);
  router.put('/contracts/:id/terminations/:terminationId/replacement-procurement', controller.upsertReplacementProcurement);
  router.put('/contracts/:id/closeout', controller.upsertCloseout);
  router.put('/contracts/:id/supplier-performance', controller.upsertSupplierPerformance);
  router.put('/contracts/:id/warranties', controller.upsertWarranty);
  router.put('/contracts/:id/required-documents', controller.upsertRequiredDocument);
  router.put('/contracts/:id/workflow-approvals', controller.upsertWorkflowApproval);
  router.patch('/contracts/:id/invoices/:invoiceId/status', controller.updateInvoiceStatus);

  return router;
}
